---
title: "Exploratory Template"
author: "Willie McRae"
date: "2016"
output: html_document
---
```{r setup, include = FALSE}
# Set Working Directory
setwd()
# Install and load packages
install.packages("tidyverse", repos="http://cran.rstudio.com/")
library(tidyverse)

```

# Load

This is an analysis of the () data set from ().  

```{r load}
# Load data

```

# First Explore

What is the structure and characteristics of the data?  

```{r explore_1}
# A meta-view of the data, views of classifications of variables etc


```

# Second Explore 

```{r explore_2}
# Look at summary statistics and quick exploratory visuals

```

# Clean

```{r clean}
# Transform each data set into a common format with correct column types

```

# Tidy

```{r tidy}
# Prepare data for visual exploration and summaries, using principles of tidy data; 
# Each row is an observation, each column is a variable

```

# Final Explore

```{r explore_3}
# How do things look now the data has been manipulated?

```

# Visualize

```{r visualize}
# Create plots

```


# Observations and recommendations

```{r observations}
# What next?


```

