---
title: "Exploratory Template"
author: "Willie McRae"
date: "2016"
output: html_document
---
This template is a starting point for exploratory data analysis.  

# Setup

```{r setup}
# Set Working Directory
setwd()
# Install and load packages
install.packages("plyr", repos="http://cran.rstudio.com/")
library(plyr)
install.packages("dplyr", repos="http://cran.rstudio.com/")
library(dplyr)
install.packages("stringr", repos="http://cran.rstudio.com/")
library(stringr)
install.packages("tidyr", repos="http://cran.rstudio.com/")
library(tidyr)
install.packages("lubridate", repos="http://cran.rstudio.com/")
library(lubridate)

install.packages("ggplot2", repos="http://cran.rstudio.com/")
library(ggplot2)

install.packages("rattle", repos="http://cran.rstudio.com/")
library(rattle) 
install.packages("rpart.plot", repos="http://cran.rstudio.com/")
library(rpart.plot)
install.packages("RColorBrewer",repos="http://cran.rstudio.com/")
library(RColorBrewer) 
library(rpart) 

```

# Load

```{r load}
# Load datasets

```

# Clean

```{r clean}
# Transform each data set into a common format with correct column types

```

# Tidy

```{r tidy}
# Prepare data for visual exploration and summaries, using principles of tidy data; 
# Each row is an observation, each column is a variable

```

# Explore

```{r explore}
# Look at summary statistics and quick exploratory visuals

```

# Visualize

```{r visualize}
# Create plots

```
